#!/usr/bin/python3

x = 0.0
xa = 1.0
xb = 1.0
for cou in range(1):
    x += (10 - 2 * xa - 1 * xb)/3
    xa += (12 - 1 * x - 1 * xb)/4
    xb += (21 - 2 * x - 2 * xa)/4
print(float(x),float(xa),float(xb))
