#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yuki Kumazawa

x = 0.0
xa = xb = 1.0
for cou in range(1):
    x += (10 - 2 * xa - 1 * xb)/3
    xa += (12 - 1 * x - 1 * xb)/4
    xb += (21 - 2 * x - 2 * xa)/5
print(float(x),float(xa),float(xb))


