#!/usr/bin/python3 
# SPDX-FileCopyrightText: 2022 Yuki Kumazawa
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
mul = 1

for line in sys.stdin:

    try: 
        ans += int(line)
        mul *= int(line)
###例外処理###
    except:
        ans += float(line)
        mul *= float(line)

print(ans,mul)
